// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ApiAgendamentos.Persistence;

namespace ApiAgendamentos.Migrations
{
    [DbContext(typeof(bancoagendamentoContext))]
    partial class AgendamentoContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiAgendamentos.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime");

                    b.Property<int>("Id_Cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Estabelecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estabelecimento");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.EstabelecimentosPessoas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EstabelecimentoId")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstabelecimentoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("EstabelecimentosPessoas");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dia_Semana")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.HorarioEmpresas", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpresaNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioNavigationId")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdEmpresaNavigationId");

                    b.HasIndex("IdHorarioNavigationId");

                    b.ToTable("HorarioEmpresas");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.HorarioPessoas", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("IdHorarioNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int?>("IdPessoaNavigationId")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdHorarioNavigationId");

                    b.HasIndex("IdPessoaNavigationId");

                    b.ToTable("HorarioPessoas");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Ocorrencia");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<int>("Id_Estabelecimento")
                        .HasColumnType("int");

                    b.Property<int>("Id_Funcionario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone1")
                        .HasColumnType("text");

                    b.Property<string>("Telefone2")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.ServicosFuncionarios", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("IdPessoaNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("IdPessoaIdFuncionario")
                        .HasColumnType("int");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("int");

                    b.HasKey("IdServico");

                    b.HasIndex("IdPessoaNavigationId");

                    b.HasIndex("ServicoId");

                    b.ToTable("ServicoFuncionarios");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Agendamento", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Empresa", null)
                        .WithMany("Agendamentos")
                        .HasForeignKey("EmpresaId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.EstabelecimentosPessoas", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Estabelecimento", "Estabelecimento")
                        .WithMany("EstabelecimentosPessoas")
                        .HasForeignKey("EstabelecimentoId");

                    b.HasOne("ApiAgendamentos.Models.Pessoa", "Pessoa")
                        .WithMany("EstabelecimentosPessoas")
                        .HasForeignKey("PessoaId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.HorarioEmpresas", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("HorarioEmpresas")
                        .HasForeignKey("IdEmpresaNavigationId");

                    b.HasOne("ApiAgendamentos.Models.Horario", "IdHorarioNavigation")
                        .WithMany("HorarioEmpresas")
                        .HasForeignKey("IdHorarioNavigationId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.HorarioPessoas", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Horario", "IdHorarioNavigation")
                        .WithMany("HorarioPessoas")
                        .HasForeignKey("IdHorarioNavigationId");

                    b.HasOne("ApiAgendamentos.Models.Pessoa", "IdPessoaNavigation")
                        .WithMany("HorarioPessoas")
                        .HasForeignKey("IdPessoaNavigationId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Ocorrencia", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Pessoa", null)
                        .WithMany("Ocorrencias")
                        .HasForeignKey("PessoaId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.Pessoa", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");
                });

            modelBuilder.Entity("ApiAgendamentos.Models.ServicosFuncionarios", b =>
                {
                    b.HasOne("ApiAgendamentos.Models.Pessoa", "IdPessoaNavigation")
                        .WithMany()
                        .HasForeignKey("IdPessoaNavigationId");

                    b.HasOne("ApiAgendamentos.Models.Servico", null)
                        .WithMany("ServicosFuncionarios")
                        .HasForeignKey("ServicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
